// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/target/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'a4773715dfd7645da4e8f474c8555dd0f507b3e790013f01095cd1dad8fdf447'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly BannedIP: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly expires: CodecTypes['mongo/date@1']['output'];
      readonly reason: CodecTypes['mongo/string@1']['output'];
    };
    readonly BannedWebhook: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly reason: CodecTypes['mongo/string@1']['output'];
    };
    readonly WebhooksSeen: { readonly _id: CodecTypes['mongo/objectId@1']['output'] };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly BannedIP: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly expires: CodecTypes['mongo/date@1']['input'];
      readonly reason: CodecTypes['mongo/string@1']['input'];
    };
    readonly BannedWebhook: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly reason: CodecTypes['mongo/string@1']['input'];
    };
    readonly WebhooksSeen: { readonly _id: CodecTypes['mongo/objectId@1']['input'] };
  };
};

export namespace Models {
  export type unbound_BannedIP = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    expires: CodecTypes['mongo/date@1']['output'];
    reason: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_BannedWebhook = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    reason: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_WebhooksSeen = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  __unbound__: {
    BannedIP: Models.unbound_BannedIP;
    BannedWebhook: Models.unbound_BannedWebhook;
    WebhooksSeen: Models.unbound_WebhooksSeen;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly bannedips: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly expires: { readonly bsonType: 'date' };
                    readonly reason: { readonly bsonType: 'string' };
                  };
                  readonly required: readonly ['_id', 'expires', 'reason'];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly bannedwebhooks: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly reason: { readonly bsonType: 'string' };
                  };
                  readonly required: readonly ['_id', 'reason'];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly seenwebhooks: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: { readonly _id: { readonly bsonType: 'objectId' } };
                  readonly required: readonly ['_id'];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly bannedips: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'BannedIP';
    };
    readonly bannedwebhooks: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'BannedWebhook';
    };
    readonly seenwebhooks: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'WebhooksSeen';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly BannedIP: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly expires: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly reason: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'bannedips' };
          };
          readonly BannedWebhook: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly reason: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'bannedwebhooks' };
          };
          readonly WebhooksSeen: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'seenwebhooks' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
