services:
  webhook-proxy:
    container_name: webhook-proxy
    image: registry.stackowoflow.com/canary/webhook-proxy:latest
    restart: unless-stopped
    networks:
      - traefik
      - internal
    depends_on:
      dragonfly:
        condition: service_healthy
    env_file:
      - stack.env

  dragonfly:
    container_name: webhook-proxy-cache
    image: ghcr.io/dragonflydb/dragonfly:latest
    networks:
      - internal
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5
      
networks:
  internal:
    external: false
  traefik:
    external: true
volumes:
  dragonflydata: