services:
  webhook-proxy:
    container_name: webhook-proxy
    image: registry.stackowoflow.com/canary/webhook-proxy:latest
    restart: unless-stopped
    networks:
      - traefik
      - internal
    depends_on:
      dragonfly:
        condition: service_healthy
    env_file:
      - stack.env

  dragonfly:
    container_name: webhook-proxy-cache
    image: ghcr.io/dragonflydb/dragonfly:latest
    restart: unless-stopped
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  traefik:
    external: true
  internal:

volumes:
  dragonflydata: