name: Publish to GitHub Packages

on:
  push:
    branches: ["master"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to GitHub Docker Repo
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u lavylavenderr --password-stdin

      - name: Build Docker Image
        run: docker build -t webhook-proxy .

      - name: Tag Docker Image
        run: docker tag webhook-proxy ghcr.io/lavylavenderr/webhook-proxy:latest

      - name: Push Docker Image
        run: docker push ghcr.io/lavylavenderr/webhook-proxy:latest
