name: Publish Image
on:
  push:
    branches: ['master']
    tags: ['v*']
jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Login to Package Registry
        run: echo "${{ secrets.LAVENDER_REGISTRY_TOKEN }}" | docker login registry.stackowoflow.com -u alexander --password-stdin

      - name: Set Image Tags
        id: tag
        run: |
          BASE_REGISTRY="registry.stackowoflow.com/canary/webhook-proxy"
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          
          echo "tag_latest=${BASE_REGISTRY}:latest" >> $GITHUB_OUTPUT
          echo "tag_sha=${BASE_REGISTRY}:sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push
        run: |
          docker build \
            --build-arg GITHUB_SHA=${{ github.sha }} \
            -t ${{ steps.tag.outputs.tag_latest }} \
            -t ${{ steps.tag.outputs.tag_sha }} \

          docker push ${{ steps.tag.outputs.tag_latest }}
          docker push ${{ steps.tag.outputs.tag_sha }}